export default {
	addNewPortfolio: "New Portfolio",
	savePortfolio: "Save Portfolio",
	deletePortfolio: "Delete Portfolio",
	addNewStrategy: "New Strategy",
	editStrategy: "Edit Strategy",
	deleteStrategy: "Delete Strategy",
	saveStrategy: "Save Strategy",
	duplicateStrategy: "Duplicate Strategy",
	mergeStrategy: "Merge Strategy",
	moveStrategy: "Move Strategy",
	addTrade: "New Trade",
	editTrade : "Edit Trade",
	saveTrade : "Save Trade",
	exitTrade : "Exit Trade",
	deleteTrade : "Delete Trade",
	showStrategyDiagram: "Update Graph",
	getLiveData : "Get Live Data",
};