export default {
  addNewPortfolio: "New portfolio",
  searchPortfolios: "Search portfolios",
  savePortfolio: "Save portfolio",
  deletePortfolio: "Remove portfolio",
  addNewStrategy: "New strategy",
  editStrategy: "Edit strategy",
  deleteStrategy: "Remove strategy",
  saveStrategy: "Save strategy",
  duplicateStrategy: "Duplicate strategy",
  mergeStrategy: "Merge into another strategy",
  moveStrategy: "Move to another portfolio",
  addTrade: "New trade",
  editTrade: "Edit trade",
  saveTrade: "Save trade",
  exitTrade: "Exit trade",
  deleteTrade: "Delete trade",
  showStrategyDiagram: "Update graph",
  showGraph: "Show payoff graph",
  hideGraph: "Hide payoff graph",
  getLiveData: "Refresh live prices",
};
