FROM node:lts-alpine
WORKDIR /server
COPY . .
RUN npm --prefix ./server install
RUN npm --prefix ./server run build
RUN cp -r ./server/dist/ /home/server
RUN cp -r ./server/node_modules /home/server
RUN cp ./server/.env /home/server/
EXPOSE 9090
CMD [ "node", "--env-file=/home/server/.env", "/home/server/index.js" ]
