apiVersion: v1
kind: Service
metadata:
  name: ptserver-api2-frmfile
  namespace: default
spec:
  selector:
    app: ptserver-api2
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: ptserver-api2
    protocol: TCP
    port: 90
    targetPort: 9090


